In [15]:
import numpy as np
import os
distance_file = os.path.join('data','data','distance_data_headers.csv')

distances = np.genfromtxt(fname=distance_file,delimiter=',', dtype='unicode', skip_header=0)

data = distances[1:,:].astype(np.float)
headers = distances[0,:]

smallData = data[0:10,0:3]
print(smallData)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [12]:
thr4_atp = data[:,1]
avg_thr4_atp = np.mean(thr4_atp)
print(avg_thr4_atp)

10.876950930000001


In [16]:
np.shape(data)

for i in range(1,5):
    column = data[:,i]
    avg_col = np.mean(column)
    print('{}:{}'.format(headers[i],avg_col))

THR4_ATP:10.876950930000001
THR4_ASP:7.342344959999999
TYR6_ATP:11.209791329999998
TYR6_ASP:10.9934435


In [52]:
# Geometry Analysis Proj
import os
import numpy as np

waterFile = os.path.join('data','data','water.xyz')
contents = np.genfromtxt(fname=waterFile, delimiter=',', dtype='unicode', skip_header=2)

data = []
for line in contents:
    data.append(line.split())
data = np.array(data)

# now we have data in a nice, indexable array

for m in range(len(contents)):
    for n in range(len(contents)):
        
        # iteratively finds the distance between the mth and nth molecule
        dist = np.sqrt(
            (float(data[m,1]) - float(data[n,1]))**2 + # x coord
            (float(data[m,2]) - float(data[n,2]))**2 + # y coord
            (float(data[m,3]) - float(data[n,3]))**2   # z coord
        )
        
        print('{} to {}: \t {}'.format(data[m,0],data[n,0],dist))



O to O: 	 0.0
O to H1: 	 0.9690005374652793
O to H2: 	 0.9690003348647513
H1 to O: 	 0.9690005374652793
H1 to H1: 	 0.0
H1 to H2: 	 1.52693633514957
H2 to O: 	 0.9690003348647513
H2 to H1: 	 1.52693633514957
H2 to H2: 	 0.0


In [55]:
# Geometry Analysis Proj ext 1,2,3
import os
import numpy as np

waterFile = os.path.join('data','data','water.xyz')
contents = np.genfromtxt(fname=waterFile, delimiter=',', dtype='unicode', skip_header=2)

data = []
for line in contents:
    data.append(line.split())
data = np.array(data)

# now we have data in a nice, indexable array

newFile = open('bond_lengths.txt','w+')

for m in range(len(contents)):
    for n in range(m+1,len(contents)): # n with range(m+1,len) yields no duplication
        
        # iteratively finds the distance between the mth and nth molecule
        dist = np.sqrt(
            (float(data[m,1]) - float(data[n,1]))**2 + # x coord
            (float(data[m,2]) - float(data[n,2]))**2 + # y coord
            (float(data[m,3]) - float(data[n,3]))**2   # z coord
        )
        
        if dist < 1.5:
            message = '{} to {}: \t {}'.format(data[m,0],data[n,0],dist)
            print(message)
            newFile.write(message)
            



O to H1: 	 0.9690005374652793
O to H2: 	 0.9690003348647513


In [1]:
import os,glob

fileLocs = os.path.join('data','data','*.xyz')
filenames = glob.glob(fileLocs)

for f in filenames:
    

['data\\data\\benzene.xyz', 'data\\data\\buckminsterfullerene.xyz', 'data\\data\\water.xyz']
